<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.by1337.blib</groupId>
    <artifactId>Blib-parent</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>
    <name>Blib-parent</name>

    <properties>
        <revision>1.9.8</revision>
    </properties>

    <modules>
        <module>BLib</module>
        <module>BLib-api</module>
        <module>MinimessageSupport</module>
        <module>BLib-Nbt</module>
        <module>ShadedDFU</module>
    </modules>
    <build>
        <defaultGoal>clean install</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <distributionManagement>
        <repository>
            <id>by1337.repo.2</id>
            <name>releases</name>
            <url>https://repo.by1337.space/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>by1337.repo.2</id>
            <name>snapshots</name>
            <url>https://repo.by1337.space/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
</project>
