name: BLib
version: '${project.version}'
main: org.by1337.lib.BLib
api-version: '1.16'
author: "By1337"
softdepend:
  - 'PlaceholderAPI'
commands:
  blib:
    aliases: lib
permissions:
  blib.*:
    default: op