name: BLib
version: '${project.version}'
main: org.by1337.blib.core.BLib
api-version: '1.16'
author: "By1337"
depend:
  - WorldEdit
softdepend:
  - 'PlaceholderAPI'
#commands:
#  blib:
#    aliases: lib
permissions:
  blib.*:
    default: op